menu:
  # script:
  #   name: scripts
  #   url_path: /admin/scripts
  #   icon: chart
  #   current: ['admin/scripts']
  #   model: Script
  # script:
  #   name: scripts
  #   url_path: /admin/scripts
  #   icon: chart
  #   current: ['admin/scripts']
  #   model: Script
  # seo:
  #   name: SEO
  #   current: ['admin/meta_tags']
  #   icon: graph
  #   model: MetaTag
  #   submenu:
  #     - meta_tags:
  #         name: 'Title & Metas'
  #         url_path: /admin/meta_tags
  #         current: ['admin/meta_tags']
  operative_plan:
    name: 'operative plans'
    url_path: /admin/operative_plans
    icon: layers
    current: ['admin/operative_plans']
    model: OperativePlan
  # objective:
  #   name: objectives
  #   url_path: /admin/objectives
  #   icon: layers
  #   current: ['admin/objectives']
  #   model: Objective
  # task:
  #   name: tasks
  #   url_path: /admin/tasks
  #   icon: layers
  #   current: ['admin/tasks']
  #   model: Task
  # responsable:
  #   name: responsables
  #   url_path: /admin/responsables
  #   icon: layers
  #   current: ['admin/responsables']
  #   model: Responsable
  # user:
  #   name: users
  #   url_path: /admin/users
  #   icon: user
  #   current: ["admin/users"]
  #   model: User
  # customize:  
  #   name: keppler design
  #   icon: pencil
  #   current: ['admin/customizes']
  #   model: Customize
  #   submenu:
  #     - customize:
  #         name: frontend templates
  #         url_path: /admin/customizes
  #         current: ['admin/customizes']
  #     - appearance:
  #         name: admin appearance
  #         url_path: /admin/settings/appearance
  #         current: ['appearance']
  # development:
  #   name: Development
  #   current: ['admin/scaffolds']
  #   icon: screen-desktop
  #   model: Scaffold
  #   submenu:
  #     - scaffolds:
  #         name: Keppler scaffolds
  #         url_path: /admin/scaffolds
  #         current: ['/admin/scaffolds']
